project_id = "egrwijzbxxhkhrrelsgi"

[api]
enabled = true
port = 54321
max_rows = 1000

[functions.verify-shopify-proxy]
verify_jwt = false

[functions.shopify-proxy-entry]
verify_jwt = false

[functions.upload-audio]
verify_jwt = false

[functions.generate-login-token]
verify_jwt = false

[functions.verify-login-token]
verify_jwt = false

[functions.generate-session-token]
verify_jwt = false

[functions.get-customer-data]
verify_jwt = false

[functions.create-license-code]
verify_jwt = false

[functions.list-license-codes]
verify_jwt = false

[functions.search-shopify-customers]
verify_jwt = false

[functions.get-customer-metafields]
verify_jwt = false

[functions.update-customer-metafield]
verify_jwt = false

[functions.update-license-code]
verify_jwt = false

[functions.redeem-license-code]
verify_jwt = false

[functions.assign-code-to-customer]
verify_jwt = false

[functions.get-customer-licenses-sessions]
verify_jwt = false

[functions.start-turn]
verify_jwt = false

[functions.get-game-state]
verify_jwt = false

[functions.game-websocket]
verify_jwt = false

[functions.update-turn-secret]
verify_jwt = false

[functions.update-session-theme]
verify_jwt = false

[functions.save-lobby-secret]
verify_jwt = false
