project_id = "egrwijzbxxhkhrrelsgi"

[api]
enabled = true
port = 54321
max_rows = 1000

[functions.verify-shopify-proxy]
verify_jwt = false

[functions.shopify-proxy-entry]
verify_jwt = false

[functions.upload-audio]
verify_jwt = false
